language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules

jobs:
  include:
    - name: 'Lint'
      script:
        - npm run lint
    - name: 'Unit Tests'
      script:
        - npm t
